---

- name: Setup AWS EC2 instance
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    project_name: test
    subnet_id: "subnet-0b39def18bc316f75"
    instance_type: t2.micro
    ami: ami-0c1c30571d2dae5c9
    key_name: "{{ project_name }}-key-pair"
    security_group_name: default
    tag_name: "{{ project_name }}-instance"
    state: "absent"
  tasks:
    - name: Create a new EC2 key
      amazon.aws.ec2_key:
        name: "{{ key_name }}"
        state: "{{ state }}"
      register: ec2_key

    - name: Launch EC2 Instance
      amazon.aws.ec2_instance:
        key_name: "{{ ec2_key.key.name | default(omit) }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami }}"
        state: "{{ state }}"
        vpc_subnet_id: "{{ subnet_id }}"
        security_group: "{{ security_group_name }}"
        tags:
          Name: "{{ tag_name }}"
        wait: true
      register: ec2

    - name: Print outputs
      ansible.builtin.debug:
        msg:
          - "Private IP Address: {{ ec2.instances[0].private_ip_address }}"
          - "Instance user SSH key: {{ ec2_key.key.private_key }}"
      when: state == "present"

    - name: Create template
      ansible.builtin.template:
        mode: "0600"
        src: output_template.j2
        dest: output.json
      when: state == "present"
