name: Build
on:
  workflow_call:

jobs:
  build:
    name: Build
    container: ubuntu:latest
    runs-on:
      - self-hosted
      - k8s-api
      - linux-arm64-s

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: sshpass

      - name: Build
        id: build
        run: |
          apt update
          apt install sshpass -y
          sshpass -p "raspberry" ssh pi@172.22.187.21 lscpu

          echo "This is a new patchset"
