name: Build
on:
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          file: ./template.Dockerfile
          push: false
          tags: hitachiastemo-tools/tools:latest
          secrets: |
            "aws=${{ secrets.aws }}"
          build-args: |
            "PACKAGE_NAME="hitachiastemo-tools""
            "VERSION="5.0.0""
            "RELEASE_NUM="1""
            "ARCH="all""
            "DESCRIPTION="Customized LLVM""
            "SRC_FOLDER="hitachiastemo-tools""
            "DST_FOLDER="tools""
            "HOMEPAGE="https://www.hitachiastemo.com""
            "DEPS="libc6""
            "MAINTAINER_NAME="hitachiastemo""
            "MAINTAINER_EMAIL="ha@dropmail.cc""
