name: Build
on:
  workflow_call:

jobs:
  build:
    name: Build
    container: ubuntu:latest
    runs-on:
      - self-hosted
      - k8s-api
      - linux-arm64-s

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run sshpass commands
        uses: matheusvanzan/sshpass-action@v2
        with:
          host: 172.22.187.21
          user: pi
          pass: raspberry
          run: |
            lscpu

      - name: Build
        id: build
        run: |

          echo "This is a new patchset"
