name: Main manual pipeline

on:
  workflow_dispatch:
    inputs:
      Version:
        description: 'Package version'
        required: true
        default: 1.0.0
        type: number
      ReleaseNum:
        description: 'Release Num'
        required: true
        default: 1
        type: number
      Architecture:
        description: 'Architecture'
        required: true
        default: 'all'
        type: choice
        options:
        - all
        - arm64
        - amd64



jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          file: ./template.Dockerfile
          push: false
          tags: hitachiastemo-tools/tools:latest
          secrets: |
            "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}"
            "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          build-args: |
            PACKAGE_NAME=${{ vars.PACKAGE_NAME }}
            VERSION=${{ inputs.Version }}
            RELEASE_NUM=${{ inputs.ReleaseNum}}
            ARCH=${{ inputs.Architecture}}
            DESCRIPTION=Customized LLVM
            SRC_FOLDER=hitachiastemo-tools
            DST_FOLDER=tools
            HOMEPAGE=https://www.hitachiastemo.com
            DEPS=libc6
            MAINTAINER_NAME=${{ github.actor }}
            MAINTAINER_EMAIL=ha@dropmail.cc
            APT_REPO_S3=${{ vars.APT_REPO_S3 }}
            AWS_REGION=${{ vars.AWS_REGION }}
